# docker-compose.yml

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/firedb
      - REDIS_URL=redis://redis:6379
      - MAPBOX_TOKEN=pk.eyJ1IjoidGhlbzExNTgiLCJhIjoiY21iYTU2dzdkMDBqajJub2tmY2c4Z3ltYyJ9.9-DIZmCBjFGIb2TUQ4QyXg
    depends_on:
      - db
      - redis
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
      - ./scripts:/app/scripts
      - ./data:/app/data

  db:
    image: kartoza/postgis:15-3.3
    platform: linux/arm64/v8
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=firedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: